---
title: "Intro_to_R_Homework"
output: github_document
---

  
```{r}
meta <- data.frame(
  sample=c("sample1","sample2","sample3","sample4","sample5","sample6","sample7","sample8","sample9","sample10","sample11","sample12"),
  sex=c("M","F","M","F","M","F","M","F","M","F","M","F"),
  stage=c("I","II","II","I","II","II","I","II","II","I","II","II"),
  treatment=c("A","A","A","A","B","B","B","B","P","P","P","P"),
  myc=c(2343,457,4593,9035,3450,3524,958,1053,8674,3424,463,5105)
)
```

```{r}
print(meta)
```
```{r}
sex=c("M","F","M","F","M","F","M","F","M","F","M","F")
treatment=c("A","A","A","A","B","B","B","B","P","P","P","P")
t <- treatment[c(TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE)]
s <- sex[c(1,2,1,2,1,2,1,2,1,2,1,2)]
print(t)
print(s)
```

```{r}
t1 <-treatment[c(5,7,9,10)]
print(t1)
```

```{r}
newmeta <- subset(meta, treatment == "P" )
print(newmeta)
```
```{r}
library(dplyr)
newmeta1 <- select(filter(meta, myc > 5000), stage, treatment)
print(newmeta1)
```

```{r}
metadrop = select(meta, -treatment)
metadrop
```
```{r}
new_meta <- meta[-c(7,8,9),]
print(new_meta)
```
```{r}
meta[c(1:6),]
```
```{r}
meta$pre_treatment <- c("T", "F", "F", "F", "T", "T", "F", "T", "F", "F", "T", "T")
v <-meta
print(v)
```
```{r}
colnames(meta) <- c('A','B','C','D' )
meta
```


